---
- name: add apt key for nodesource
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: add repo for nodesource
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{node_version}} {{ansible_distribution_release}} main"
    update_cache: yes

- name: install
  apt: name=nodejs state=present
