---
metrics_folder: "{{ansible_env.HOME}}/metrics"

volumes:
  - prometheus-storage
  - grafana-storage

grafana_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34656265363330646333386634376363613933303566303561306432343037383038366235313937
          3339383139653434356265636136626135356631316362300a663361666563633233306332306239
          35383931313132373161636335623930333537303738343739376636623732616662343836303939
          6435326233333962300a373263653339316438353136393133313836346330313933653466353666
          32396138666663336165336437636461646165663736303832626235386634323931
...
